# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: willbchang
custom: https://willbc.cn/#/donation?PayPal?Alipay?Wechat
